import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * https://github.com/Kotlin/kotlinx.serialization
     */
    const val kotlinx_serialization_runtime: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-runtime:" +
            Versions.org_jetbrains_kotlinx_kotlinx_serialization

    const val kotlinx_serialization_runtime_native: String =
            "org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:" +
            Versions.org_jetbrains_kotlinx_kotlinx_serialization

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:" +
            Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_core_common: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core-common:" +
            Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    const val kotlinx_coroutines_core_native: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core-native:" +
            Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions: String =
            "org.jetbrains.kotlin:kotlin-android-extensions:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_android_extensions_runtime: String =
            "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_common: String = "org.jetbrains.kotlin:kotlin-stdlib-common:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib_jdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_test: String = "org.jetbrains.kotlin:kotlin-test:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_test_annotations_common: String =
            "org.jetbrains.kotlin:kotlin-test-annotations-common:" + Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_test_common: String = "org.jetbrains.kotlin:kotlin-test-common:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_test_junit: String = "org.jetbrains.kotlin:kotlin-test-junit:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_fragment_ktx: String = "androidx.navigation:navigation-fragment-ktx:" +
            Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_safe_args_gradle_plugin: String =
            "androidx.navigation:navigation-safe-args-gradle-plugin:" + Versions.androidx_navigation

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:" +
            Versions.androidx_navigation

    /**
     * https://github.com/google/dagger
     */
    const val dagger: String = "com.google.dagger:dagger:" + Versions.com_google_dagger

    /**
     * https://github.com/google/dagger
     */
    const val dagger_compiler: String = "com.google.dagger:dagger-compiler:" +
            Versions.com_google_dagger

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_auth: String = "io.ktor:ktor-client-auth:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_auth_jvm: String = "io.ktor:ktor-client-auth-jvm:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_core: String = "io.ktor:ktor-client-core:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_core_jvm: String = "io.ktor:ktor-client-core-jvm:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_curl: String = "io.ktor:ktor-client-curl:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_ios: String = "io.ktor:ktor-client-ios:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_logging: String = "io.ktor:ktor-client-logging:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_logging_jvm: String = "io.ktor:ktor-client-logging-jvm:" +
            Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_okhttp: String = "io.ktor:ktor-client-okhttp:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_serialization: String = "io.ktor:ktor-client-serialization:" +
            Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_client_serialization_jvm: String = "io.ktor:ktor-client-serialization-jvm:" +
            Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_utils: String = "io.ktor:ktor-utils:" + Versions.io_ktor

    /**
     * https://github.com/ktorio/ktor
     */
    const val ktor_utils_jvm: String = "io.ktor:ktor-utils-jvm:" + Versions.io_ktor

    const val ktor_client_auth_native: String = "io.ktor:ktor-client-auth-native:" +
            Versions.io_ktor

    const val ktor_client_core_native: String = "io.ktor:ktor-client-core-native:" +
            Versions.io_ktor

    const val ktor_client_logging_native: String = "io.ktor:ktor-client-logging-native:" +
            Versions.io_ktor

    const val ktor_utils_native: String = "io.ktor:ktor-utils-native:" + Versions.io_ktor

    /**
     * https://developer.android.com/studio
     */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    const val de_fayard_refreshversions_gradle_plugin: String =
            "de.fayard.refreshVersions:de.fayard.refreshVersions.gradle.plugin:" +
            Versions.de_fayard_refreshversions_gradle_plugin

    /**
     * http://tools.android.com
     */
    const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
            Versions.constraintlayout

    /**
     * https://developer.android.com/testing
     */
    const val espresso_core: String = "androidx.test.espresso:espresso-core:" +
            Versions.espresso_core

    /**
     * https://developer.android.com/studio
     */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * https://jax-ws.dev.java.net/
     */
    const val jsr250_api: String = "javax.annotation:jsr250-api:" + Versions.jsr250_api

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

    /**
     * https://developer.android.com/testing
     */
    const val junit_ktx: String = "androidx.test.ext:junit-ktx:" + Versions.junit_ktx

    /**
     * https://developer.android.com/jetpack/androidx
     */
    const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

    /**
     * https://developer.android.com/studio
     */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2
}
