import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_serialization: String = "0.13.0"

    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.3.2"

    const val org_jetbrains_kotlin: String = "1.3.50" // available: "1.3.60"

    const val androidx_navigation: String = "2.1.0"

    const val com_google_dagger: String = "2.25.2"

    const val io_ktor: String = "1.3.0-beta-1"

    const val com_android_tools_build_gradle: String = "3.5.2"

    const val de_fayard_refreshversions_gradle_plugin: String = "0.7.0" // available: "0.8.4"

    const val constraintlayout: String = "1.1.3"

    const val espresso_core: String = "3.2.0"

    const val lint_gradle: String = "26.5.2"

    const val jsr250_api: String = "1.0" // available: "1.0-20050927.133100"

    const val appcompat: String = "1.1.0"

    const val junit_ktx: String = "1.1.1"

    const val core_ktx: String = "1.1.0"

    const val aapt2: String = "3.5.2-5435860"

    /**
     * Current version: "5.6.3"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.0.1"
}
