import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_serialization: String = "0.14.0"

    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.3.3"

    const val com_squareup_sqldelight: String = "1.2.1" // available: "1.2.2"

    const val androidx_databinding: String = "3.6.0"

    const val org_jetbrains_kotlin: String = "1.3.61"

    const val androidx_navigation: String = "2.2.1"

    const val androidx_lifecycle: String = "2.2.0"

    const val com_google_dagger: String = "2.26"

    const val co_touchlab: String = "0.9.4"

    const val io_mockk: String = "1.9.3"

    const val io_ktor: String = "1.3.1"

    const val com_android_tools_build_gradle: String = "3.6.0"

    const val de_fayard_refreshversions_gradle_plugin: String = "0.7.0" // available: "0.9.2"

    const val constraintlayout: String = "1.1.3"

    const val espresso_core: String = "3.2.0"

    const val core_testing: String = "2.1.0"

    const val lint_gradle: String = "26.6.0"

    const val byte_buddy: String = "1.10.8"

    const val jsr250_api: String = "1.0" // available: "1.0-20050927.133100"

    const val appcompat: String = "1.1.0"

    const val junit_ktx: String = "1.1.1"

    const val core_ktx: String = "1.2.0"

    const val aapt2: String = "3.6.0-6040484"

    const val klock: String = "1.8.6"

    const val mvvm: String = "0.4.0"

    /**
     * Current version: "6.2.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.2.1"
}
